language: csharp

# branches:
#   only:
#   - dev
#   - master

os:
  - linux
dist: trusty
sudo: required

before_install:
  - 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" | sudo tee -a /etc/apt/sources.list'
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y dotnet-dev-1.0.0-preview2-003121

script:
  - ./build.sh

cache:
  directories:
    - $HOME/.local/share/NuGet/Cache
    - $HOME/.nuget/packages
    - tools